version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine3.18
    volumes:
      - /Users/aushkov/Applications/matcha_volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - db.env
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    volumes:
      - /Users/aushkov/Applications/pgadmin_volume:/var/lib/pgadmin
    env_file:
      - db.env
    
  #matcha:
    #container_name: matcha
    #build: .
    #restart: always
    #ports:
    #  - '8080:8080'
    #depends_on:
    #  - postgres
    