name: Update code on VM

on:
  push:
    branches:
      - main

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'

      - name: 'ssh-launch-script'
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: 'matcha-instance'
          zone: 'us-west1-a'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          script: |
            echo "Listing home directory contents:"
            ls -la /home/jamatchaserver
            echo "Checking if script.sh exists and is executable:"
            if [ -x "/home/jamatchaserver/script.sh" ]; then
              echo "script.sh exists and is executable."
            else
              echo "script.sh does not exist or is not executable."
              exit 1
            fi
          