name: Update code on VM

on:
  push:
    branches:
      - main

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:
      - name: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'

      - name: 'ssh-launch-script'
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: 'matcha-instance'
          zone: 'us-west1-a'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          script: |
            pwd
            echo "Listing home directory contents:"
            ls -la /home/jamatchaserver
            echo "Checking if matcha-backend directory exists:"
            if [ -d "/home/jamatchaserver/matcha-backend" ]; then
              echo "Directory exists."
            else
              echo "Directory does not exist."
              exit 1
            fi
            cd /home/jamatchaserver/matcha-backend
            git pull
            docker compose up -d --build --force-recreate matcha